### ISSUE TITLE
Set value function

### ISSUE THREAD

**Issue by thewayiam** [EdouardTack/candlestick#1]
Is there any chance to set this element to on/off/middle from javascript?

**Comment by EdouardTack** [comment]
Hello,
The value is set with the value attribute of the input element or with user action, but there's not option to change a candlestick element dynamically.
It can be like this:
`$('#element').candlestick('on');`

It's an upgrade that can be done.

**Comment by thewayiam** [comment]
That will be great!

**Comment by thewayiam** [comment]
I've made one commit for this, might need your review, thanks!
https://github.com/thewayiam/candlestick/commit/efbe48bbc54ea90cac62307248a16a7e1695289f

**Comment by thewayiam** [comment]
I found [this line](https://github.com/thewayiam/candlestick/commit/efbe48bbc54ea90cac62307248a16a7e1695289f#diff-5b533c42e7b02268edd4b6dd2290db13R88) in my repo will overwrite the options with default, don't know how to use the already exist options??

**Comment by EdouardTack** [comment]
It's okay for me the on/off case.
The options are defined in `this.settings` in Candlestick Object.
