### ISSUE TITLE
toggle left size with BS accordion

### ISSUE THREAD

**Issue by richardalain83** [EdouardTack/candlestick#12]
When using Bootstrap's Accordion, all toggle inside hidden panel have a wrong left value (in my case -20px) instead of 40px (default value for center toggle not on or off).
Is there a way to fix this?

Edit: One workaround I've found is to expand all panels with $('panel-collapse').collapse('show'), then load my candlestick code and finally collapse the panel again with $('panel-collapse').collapse('hide').

Thanks

**Comment by EdouardTack** [comment]
Hello,
It's fixed ?

Edouard

**Comment by richardalain83** [comment]
Hi, well, it's a workaround, not perfect but it's working.
Thanks for the follow up.
