### ISSUE TITLE
afterAction can't get (input,wrapper,action)

### ISSUE THREAD

**Issue by xibman** [EdouardTack/candlestick#14]
Hi edouard,

if you put something into the afterAction you can't get input or wrapper or action

**Comment by EdouardTack** [comment]
Hi,
I don't understand your question !!
Can you show me your example code ?

Edouard

**Comment by xibman** [comment]
for exemple if you try do to something like this:

``` javascript
afterAction: function(input,wrapper,action){
  $('.js-candlestick').not(input).candlestick('default');
}
```

input or wrapper or action retrun undefined

**Comment by EdouardTack** [comment]
Ok i see, it's resolve.
