### ISSUE TITLE
Initialize control

### ISSUE THREAD

**Issue by rodrigo2000** [EdouardTack/candlestick#15]
How can I initialize the control with checked value?
Checkbox fails with checked = true

**Comment by rodrigo2000** [comment]
Checking your code I found that validate that the data type also matches, so when changing my on: 1 to on: '1' already activated the control.

**Comment by EdouardTack** [comment]
Hello,
Do you have found your problem ?

Edouard

**Comment by rodrigo2000** [comment]
Yes
