### ISSUE TITLE
Couldn't move back to middle while in options mode

### ISSUE THREAD

**Issue by thewayiam** [EdouardTack/candlestick#2]
Might couse of [this line](https://github.com/EdouardTack/candlestick/blob/master/lib/css/candlestick.css#L129-L131), if I change it to:

```
    .candlestick-wrapper.candlestick-contents .candlestick-bg .candlestick-nc {
        left: 100px;
    }
```

could fixed this, I would like to send a PR if this is acceptable to you.

**Comment by EdouardTack** [comment]
You use the 'options' mode, and you can't move to middle with click ?

**Comment by thewayiam** [comment]
Yes, because this [three line](https://github.com/EdouardTack/candlestick/blob/fe915ed5822dd54f1c255aafc6656bff56550d0f/lib/css/candlestick.css#L129-L131) overwrite the above default size left property at [this line](https://github.com/EdouardTack/candlestick/blob/fe915ed5822dd54f1c255aafc6656bff56550d0f/lib/css/candlestick.css#L82), so the candlestick-nc is out of this box while in default options mode.
could fix it by replace origin one:

```
.candlestick-wrapper .candlestick-bg .candlestick-nc {
    left: 100px;
}
```

with:

```
.candlestick-wrapper.candlestick-contents .candlestick-bg .candlestick-nc {
    left: 100px;
}
```

which I think is just a typo.

**Comment by EdouardTack** [comment]
Thanks for contributions
