### ISSUE TITLE
Toggle on not in the right position when manually adjust the size of toggle

### ISSUE THREAD

**Issue by thewayiam** [EdouardTack/candlestick#3]
While adjust the width of toggle, e.g. smaller toggle, then it will make the toggle left a little room when move it to "on" as below: 
![image](https://cloud.githubusercontent.com/assets/4479861/16107589/e6026eae-33cf-11e6-9c4b-73f3b5e89a2d.png)

I think this might couse from [this line](https://github.com/EdouardTack/candlestick/blob/efbe48bbc54ea90cac62307248a16a7e1695289f/lib/js/candlestick.js#L317), if we could change the candlestick-on to candlestick-toggle as `var left = this.parent.outerWidth() - this.parent.find('.candlestick-toggle').outerWidth();`, it will allow us to modify the toggle size, what do you think?
If that's acceptable to you, I would like to send a PR!

**Comment by EdouardTack** [comment]
Can you show me the candlestick code that you use. I will test this.

**Comment by thewayiam** [comment]
I use candlestick.js in /lib/js/ https://github.com/EdouardTack/candlestick/tree/master/lib/js
I'm overwrite the toggle width to made this problem happen, you can reproduce it by change the width to 10px at [this line](https://github.com/EdouardTack/candlestick/blob/fe915ed5822dd54f1c255aafc6656bff56550d0f/lib/css/candlestick.css#L49).
