### ISSUE TITLE
Callback functions specified while initiation are triggered twice 

### ISSUE THREAD

**Issue by dhiva** [EdouardTack/candlestick#9]
I am trying to make ajax calls on the afterSetting callback but the callback function is triggered twice. It looks like the afterSetting is triggered when the click action is performed and then once the state is changed to the new state. Is it possible to have something like afterFinish callback which would be executed once all the settings are complete or change this behaviour of the afterSetting to be called only once. This happens only when the candlestick mode is set to content.

Here is the [link](http://plnkr.co/edit/koFDpB6iIZbVmMnv8lTV?p=preview) to the test code demonstrating the behaviour.

A change to the way callback works for content mode would be really helpful.

**Comment by EdouardTack** [comment]
hello,
In your example, i have only one log message in my console after set on or off or default value.
In my code, i use afterSetting in [this method](https://github.com/EdouardTack/candlestick/blob/master/lib/js/candlestick.js#L325) and his called only once.

You use the last version ?
I will test this in local.

But the afterFinish callback can be add, it will be useful i think.

Edouard

**Comment by dhiva** [comment]
I think my example was modified. When the mode is set to "contents" thats when I see this issue. in "options" code it works as expected and the "afterSetting" callback is triggered only once. 

I am using the latest version of the code the repository.

**Comment by EdouardTack** [comment]
Can you show me your code (The candlestick call) ? Thx

Edouard

**Comment by EdouardTack** [comment]
No bug find for me.
afterFinish feature is not a good update. The afterSetting callback do the job.

I close this issue
